export const categoryMapping: Record<string, string> = {
  "1A": "Amino Acids",
  "1B": "Molecular Biology",
  "1C": "Genetics",
  "1D": "Metabolism",
  "2A": "Cell Biology",
  "2B": "Cell Biology",
  "2C": "Reproduction",
  "3A": "Musculoskeletal, Endocrine, Nervous",
  "3B": "Circulation + Respiration",
  "4A": "Mechanics and Energy",
  "4B": "Fluids & Gases",
  "4C": "Circuits",
  "4D": "Light and Sound",
  "4E": "Atomic Theory",
  "5A": "Solutions and Electrochemistry",
  "5B": "Interactions of Chem Substances",
  "5C": "Lab Techniques",
  "5D": "Organic Chemistry",
  "5E": "Thermochem, Kinetics, Eq (15Q)",
  "6A": "Sensation, Perception, Consciousness",
  "6B": "Sensation, Perception, Consciousness",
  "6C": "Sensation, Perception, Consciousness",
  "7A": "Motivations, Attitude, Personality",
  "7B": "Learning, Memory, and Cognition",
  "7C": "Learning, Memory, and Cognition",
  "8A": "Identity and Social Interactions",
  "8B": "Identity and Social Interactions",
  "8C": "Identity and Social Interactions",
  "9A": "Dem. and Social Structure",
  "9B": "Dem. and Social Structure",
  "10A": "Dem. and Social Structure"
}; 