export const mymcatTopicsMapping: Record<string, string[]> = {
    "1A": ["Amino Acids", "Enzymes", "Proteins"],
    "1B": ["DNA and Biotechnology", "Eukaryotic Gene Expression", "RNA and The Central Dogma"],
    "1C": ["Evolution", "Genetics", "Meiosis and Genetic Diversity"],
    "1D": ["Aerobic Respiration", "Bioenergetics and Regulation of Metabolism", "Glycolysis, Glycogen, Gluconeogenesis, and The Pentose Phosphate Pathway", "Lipid and Amino Acid Metabolism"],
    "2A": ["Plasma Membrane", "The Cell"],
    "2B": ["Prokaryotes", "Viruses"],
    "2C": ["Embryogenesis", "Mitosis"],
    "3A": ["Endocrine System", "Nervous System"],
    "3B": ["Digestion System", "Excretion System", "Immune System", "Muscular System", "Reproductive System", "Respiration and Circulation", "Skin and Bones"],
    "CARs": ["Foundations of Comprehension", "Reasoning Beyond the Text", "Reasoning Within the Text"],
    "4E": ["Atoms", "Periodic Trends", "Stoichiometry"],
    "5A": ["Acid-Base", "Solutions"],
    "5B": ["Covalent Bonds", "Intermolecular Forces"],
    "5C": ["Seperations and Purifications", "Spectroscopy"],
    "5D": ["Carbohydrate Structure and Function", "Lipid Structure and Function", "Organic Compounds"],
    "5E": ["Enzyme Kinetics", "Equilibrium", "Thermodynamics and Thermochemistry"],
    "6A": ["Perception", "Sensation"],
    "6B": ["Cognition", "Memory and Language"],
    "6C": ["Emotions and Stress"],
    "7A": ["Biology and Behavior", "Motivation and Attitudes", "Personality"],
    "7B": ["Social Processes on Communities", "Social Processes on Individuals"],
    "7C": ["Attitude and Behavior Change", "Learning"],
    "8A": ["Social Stratification", "Self-Identity"],
    "8B": ["Attribution", "Stereotypes and Bias"],
    "8C": ["Self Presentation", "Social Interaction"],
    "9A": ["Culture", "Social Institutions"],
    "9B": ["Demographic Shift", "Demographic Structure"],
    "10A": ["Social Stratification", "Self-Identity"],
}